services:
  webserver:
    image: php:7.4.3-apache
    ports:
      - "8181:80"
    volumes:
      - ./UnamWebPanel:/var/www/html
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/db && chmod -R 777 /var/www/html/db && apache2-foreground"
